### ISSUE TITLE
confusion parsing `uint32` vs `uint8[4]`

### ISSUE THREAD

**Issue by getify** [vjeux/jParser#2]
My guess is this is probably an endian'ness problem, but if I am parsing out a "4 byte unsigned int" from a file format (in this case, PNG), I would have expected to be able to use `uint32` and get it out. But I get the totally wrong value.

If I instead do an array of four `uint8`s, I see the values that I want, in big-endian order. My guess is that this library is converting the `uint32` in little-endian order?

Is there a way to tell the lib to do it in big-endian?

Or is it something else wrong that I don't understand?

**Comment by vjeux** [comment]
It is using jDataView behind the scenes. https://github.com/vjeux/jDataView

You can specify the endianess this way:

```
var view = new jDataView(file, undefined, undefined, /* littleEndian */ false);
var parser = new jParser(view);
```

**Comment by getify** [comment]
Yup, setting it to bigEndian mode manually did the trick. Thanks.
